---
common_timezone: "{{ timezone | default('Asia/Jakarta') }}"
common_locale: "{{ system_locale | default('en_US.UTF-8') }}"
common_packages_list: "{{ common_packages }}"
common_sysctl: "{{ sysctl_settings }}"
common_journald_limit: "{{ journald_max_use | default('500M') }}"
